This is to discuss an idea for an application and platform supporting *personal information management* on the *Desktop* and/or personal server.

== Goals

. Integrate as much of a user's personal information as feasible and provide an *integrated view* on all local and eventually remote sources.
The information should be searchable, filterable and editable.
. Suitable for multiple types of (primarily textual) resources: notes, tasks, playlists, slideshows, bookmarks, blog posts etc.
. *Slim UI* with browser-like navigation, history, bookmarks, session management and tab/window-handling.
. The platform should allow easy extension (as well as reduction) of functionality, for which as much as possible will be realized as plugins.
. The application will encourage the use of *lightweight markup languages* and *local storage* to preserve the personal information sovereignity.
. Every view in the application (even on single files) is accessible using *stable URLs*, even if the storage locations may change.

== Technology

* In order to be platform independent and properly integrated into the user's desktop environment, the programming language will be *Java*. Other JVM languages should be easily usable as well.
* A REST-API will enable multiple UIs, either web-based or Deskop using e. g.  *JavaFX*.
* Search will be based on *Lucene*, or maybe Elastic Search.
* Initially supported textual markups will be *Markdown* and *Asciidoctor*.

== Inspirations

* http://zim-wiki.org/[ZIM Desktop Wiki]
* http://rednotebook.sourceforge.net/[RedNotebook]

=== Privacy
* https://userdatamanifesto.org/[User data manifesto]
